### PR TITLE
Add arm and arm64 builds

### PR DESCRIPTION
**Pull request by danielsimkus**
Re: https://github.com/inbucket/inbucket/issues/246

👋  This should start building ARM and ARM64 builds. I'm not familiar with goreleaser myself but this seems to follow their example in the docs https://goreleaser.com/customization/build/

### CODE REVIEW

**Comment by jhillyerd** [comment]
Looks like you need to add this for inbucket-client as well, lower in the file:  release failed after 188.48s error=invalid archive: 0: archive has different count of built binaries for each platform, which may cause your users confusion. Please make sure all builds used have the same set of goos/goarch/etc or split it into multiple archives

**Comment by danielsimkus** [comment]
Ah that makes sense, will add that and also goarm 7 perhaps?

**Comment by danielsimkus** [comment]
Re discussions in https://github.com/inbucket/inbucket/issues/246 switched `goarm` to just 7.
Also one thing to note, not sure if it's an issue but the syntax checker on the `gorelease.yml` forced a string type for `goarm`, but in their documentation they use integers: https://goreleaser.com/customization/build/

Not sure if it actually matters though

**Comment by jhillyerd** [comment]
Nothing matters with yaml, it's all garbage. :)  I can see arm7 labels on the output files, so I think it works.  I think there are some more security fixes I need to merge, then I will cut another release candidate.  Thanks!

**Pull request merged**
