### PR TITLE
Add ability to name mailboxes after domain of email

### PR DESCRIPTION
**Pull request by MatthewJohn**
I am currently testing this and have not written tests (I will do this in my free time).
But raising to make awareness of the change for now and get feedback :)

### CODE REVIEW

**Comment by jhillyerd** [comment]
This seems like a good idea to me.  I've moved it to the develop branch, as that's where new work happens, master is only for stable releases.  (See CONTRIBUTING.md)

I think GitHub has added a way to mark PRs as draft to indicate they aren't ready to merge, if so, that may be a good way to indicate we are waiting for tests, etc.

**Comment by MatthewJohn** [comment]
@jhillyerd Ah, sounds good :) Originally made the changes to master, as we wanted them patched on to the latest stable, so that we could use it immediately :) But will update now!

**Comment by MatthewJohn** [comment]
From what I can see (or rather can't see), looks like you can only do this at the point of creating the PR :( So can either re-create, but comments will be lost or leave as is?
Will start working on the tests now

**Comment by jhillyerd** [comment]
In general, I don't add features without going through a beta/release candidate phase -- probably overkill for Inbucket, but given I don't have a QA team or end to end tests, makes things a bit safer.  Either way, we'd want this to land in develop first and possibly be backported to master.  But right now there is 0 functional differences between develop and master, as I haven't merged anything since releasing the beta.

**Comment by MatthewJohn** [comment]
Superseded by #140

**Pull request closed without merging**
