### PR TITLE
allow empty envelope

### LINKED ISSUE #164: Empty envelope sender is rejected
Inbucket rejects mail sent with an empty envelope sender.

`MAIL FROM:<>` is valid in SMTP, and sometimes used for low-value mail (out-of-office, receipt notifications, etc) to ensure that failed delivery will be discarded rather than causing an asynchronous bounce, and to mitigate some flavours of mail loop.

It's a very minor issue, but if fixing it were as simple as removing a check or changing a regex it'd be nice to do.

```
[9:44:34.675 8] Starting SMTP session
[9:44:34.676 9] <<< 220 inbucket Inbucket SMTP ready
[9:44:34.676 9] >>> EHLO abacus
[9:44:34.676 9] <<< 250-Great, let's get this show on the road
[9:44:34.676 9] <<< 250-8BITMIME
[9:44:34.676 9]     250 SIZE 10240000
[9:44:34.676 9] >>> MAIL FROM:<>
[9:44:34.676 9] <<< 501 Was expecting MAIL arg syntax of FROM:<address>
[9:44:34.676 9] >>> QUIT
[9:44:34.677 9] <<< 221 Goodnight and good luck
```

### PR DESCRIPTION
**Pull request by sascha-andres**
This PR will allow to use <> as MAIL FROM: parameter.

Closes #164

### CODE REVIEW

**Comment by sascha-andres** [comment]
There are tests failing but that does not seem to be related to the change I've done I think. If I'm wrong I will happily change things.

**Comment by jhillyerd** [comment]
The [tests pass online](https://travis-ci.org/github/inbucket/inbucket/builds/711068307), not sure why GitHub didn't list this as part of the checks though, I may have broken that when I added the docker image build.

There shouldn't be any failing tests though, you may want to file a bug for those if they aren't related.

**Comment by jhillyerd** [comment]
Please add a test case for this to ensure it does not get broken in the future, I'd try adding to https://github.com/inbucket/inbucket/blob/master/pkg/server/smtp/handler_test.go#L127

Note that it will likely be a while before I merge this, as I want to see how it affects the UI.  I suspect having an empty string for from will make some things ugly, which is why I mentioned setting it to "unspecified" in #164

**Comment by sascha-andres** [comment]
Added a test and set it to unspecified as you've mentioned in #164

**Comment by jhillyerd** [comment]
Thanks!

**Pull request merged**
